# Generated by Django 4.2.3 on 2023-07-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_quesmodel_delete_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('marks', models.IntegerField(max_length=20, null=True)),
            ],
        ),
    ]
