# Generated by Django 4.2.3 on 2023-09-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_py'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Py',
            new_name='Pyy',
        ),
    ]
