# Generated by Django 4.2.3 on 2023-09-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_py_pyy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Py_res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('marks', models.IntegerField(null=True)),
            ],
        ),
    ]
