# Generated by Django 4.2.3 on 2023-09-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_py_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('marks', models.IntegerField(null=True)),
            ],
        ),
    ]
